import { Geist, Geist_Mono } from "next/font/google";
import { Inknut_Antiqua, Kaushan_Script } from "next/font/google";
import "./globals.css";
import { Providers } from "./Providers"; // ✅ ini saja

const inknut = Inknut_Antiqua({
  subsets: ["latin"],
  weight: ["400", "700"],
});

const kaushan = Kaushan_Script({
  subsets: ["latin"],
  weight: ["400"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}